CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIALL PRIMARY, FUL_NAME VARCHAR(100), CPF BIGINT, EMAIL VARCHAR(100),
    "PASSWORD" VARCHAR(100), "TYPE" INT, BALANCE DECIMAL(10, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTION (
    ID SERIAL PRIMARY KEY, PAYER INT, PAYEE INT, "VALUE" DECIMAL(10, 2),
    CREATE_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES WALLETS (ID),
    FOREIGN KEY (PAYEE) REFERENCES WALLETS (ID)
);